name: mountsinai_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - monai
  - nibabel
  - simpleitk
  - streamlit
  - dash
  - plotly
